### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [3]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [4]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [5]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


In [6]:
# 創建tensor
a = torch.randn((2,3))
b = torch.randn(3)
print(a.shape, b.shape)
a, b

torch.Size([2, 3]) torch.Size([3])


(tensor([[ 1.6510,  0.1553, -0.4452],
         [ 0.6247, -0.6139,  0.1907]]), tensor([-1.1390,  0.2147, -0.5660]))

### Function 1 - torch.add(a,b)

In [7]:
# Example 1 - ### 相加
t_add1 = a + b
t_add2 = torch.add(a,b)
print(t_add1.shape, t_add2.shape)
t_add1, t_add2

torch.Size([2, 3]) torch.Size([2, 3])


(tensor([[ 0.5120,  0.3700, -1.0112],
         [-0.5143, -0.3992, -0.3753]]), tensor([[ 0.5120,  0.3700, -1.0112],
         [-0.5143, -0.3992, -0.3753]]))

### Function 2 - torch.sub(a,b)

In [8]:
# Example 1 - 相減
t_sub1 = a - b
t_sub2 = torch.sub(a,b)
print(t_sub1.shape, t_sub2.shape)
t_sub1, t_sub2

torch.Size([2, 3]) torch.Size([2, 3])


(tensor([[ 2.7899, -0.0594,  0.1208],
         [ 1.7636, -0.8287,  0.7566]]), tensor([[ 2.7899, -0.0594,  0.1208],
         [ 1.7636, -0.8287,  0.7566]]))

### Function 3 - torch.div

In [9]:
# 相除
t_div1 = a / b
t_div2 = torch.div(a,b)
print(t_div1.shape, t_div2.shape)
t_div1, t_div2

torch.Size([2, 3]) torch.Size([2, 3])


(tensor([[-1.4495,  0.7232,  0.7866],
         [-0.5485, -2.8589, -0.3369]]), tensor([[-1.4495,  0.7232,  0.7866],
         [-0.5485, -2.8589, -0.3369]]))

In [12]:
# 創建tensor
a = torch.randn((2,3,2))

print(a.shape)
a

torch.Size([2, 3, 2])


tensor([[[-0.3056,  0.7468],
         [-1.2821, -0.5625],
         [-0.2622, -0.3867]],

        [[-0.1578,  0.5157],
         [ 1.2944,  1.4754],
         [ 1.3086,  0.5624]]])

### Function 4 - torch.reshape / torch.view

In [13]:
# 將tensor形狀由[2,2,3]改為[2,6]
b = a.reshape(2, 6)
c = a.view(2, 6)
d = a.reshape(2, -1)
print(b.shape, c.shape, d.shape)
b,c,d

torch.Size([2, 6]) torch.Size([2, 6]) torch.Size([2, 6])


(tensor([[-0.3056,  0.7468, -1.2821, -0.5625, -0.2622, -0.3867],
         [-0.1578,  0.5157,  1.2944,  1.4754,  1.3086,  0.5624]]),
 tensor([[-0.3056,  0.7468, -1.2821, -0.5625, -0.2622, -0.3867],
         [-0.1578,  0.5157,  1.2944,  1.4754,  1.3086,  0.5624]]),
 tensor([[-0.3056,  0.7468, -1.2821, -0.5625, -0.2622, -0.3867],
         [-0.1578,  0.5157,  1.2944,  1.4754,  1.3086,  0.5624]]))

In [14]:
# Example 2 - ### your explanation ###
# 調換tensor維度
e = a.permute((0, 2, 1))
f = a.transpose(1,2)
print(e.shape, f.shape)
e, f

torch.Size([2, 2, 3]) torch.Size([2, 2, 3])


(tensor([[[-0.3056, -1.2821, -0.2622],
          [ 0.7468, -0.5625, -0.3867]],
 
         [[-0.1578,  1.2944,  1.3086],
          [ 0.5157,  1.4754,  0.5624]]]), tensor([[[-0.3056, -1.2821, -0.2622],
          [ 0.7468, -0.5625, -0.3867]],
 
         [[-0.1578,  1.2944,  1.3086],
          [ 0.5157,  1.4754,  0.5624]]]))

In [15]:
# 增加張量維度
g = torch.unsqueeze(a, dim=1) #增加維度在1的位置
h = torch.squeeze(g) #壓縮為度為1的位置
print(g.shape, h.shape)

torch.Size([2, 1, 3, 2]) torch.Size([2, 3, 2])
